name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 

    - name: Log into registry
      run: echo "${{ secrets.DH_PW }}" | docker login -u fwilhe --password-stdin

    - name: install debootstrap
      run: |
        sudo apt-get -y install debootstrap
    - name: build image
      run: |
        sudo debootstrap  --variant=minbase --arch=amd64  buster buster > /dev/null
        sudo tar -C buster -c . | docker import - fwilhe/buster
    - name: docker images
      run: |
        docker images
    - name: view fs
      run: |
        docker run --rm fwilhe/buster find /
    - name: view fs
      run: |
        docker push fwilhe/buster
