name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install debootstrap
      run: |
        sudo apt-get -y install debootstrap
    - name: build image
      run: |
        sudo debootstrap  --variant=minbase --arch=amd64  buster buster > /dev/null
        sudo tar -C buster -c . | docker import - buster
    - name: docker images
      run: |
        docker images
    - name: view fs
      run: |
        docker run --rm buster find /
